### ISSUE TITLE
Difficulty sending nested parameters / or lists

### ISSUE THREAD

**Issue by ghost** [sendinblue/APIv3-csharp-library#10]
Hello!

How is the correct way to send parameters with nested values?

I try to send using dictionary of <string, object> and added other dictionary in one parameter. But I was not successful.

Code:
```
Dictionary<string, object> parametersList = new Dictionary<string,object>();
Dictionary<string, string> nestedParameters = new Dictionary<string,string>();

nestedParameters("PRODUCT_NAME", "Avocado");
nestedParameters("PRODUCT_PRICE", "R$ 10,50");

parametersList.Add("COMPANYNAME", "Avocado");
parametersList.Add("DUEDATE", "18/05/2020");
parametersList.Add("PRODUCTS_LIST", nestedParameters);
```
*_the above code is just an example._

**And in my template:**

```
<ul>
{% for prod in params.PRODUCTS_LIST %}
<li>
Company: {{ prod.COMPANYNAME }}
Product Name: {{ prod.PRODUCT_NAME}}
 Product price: {{ comp.PRODUCT_PRICE }}
</li>
{% endfor %}
  </ul>
```

What am I doing wrong?

I didn't find any examples in the documentation, would it be possible to create an example with nested parameters (or parameters that have lists)?

Thanks!

**Comment by amitsendinblue** [comment]
Hi @danieljoristryideas, Which API you are using and could you please share more information which payload you want to pass (json example), so that we can assist you better.
Thanks,
Amit Joshi

**Comment by danieljoris** [comment]
Hello, @amitsendinblue ! 

I'm sorry about lack of clarity in information. 

The json example is:
```

{
  "COMPANYNAME": "Avocado",
  "DUEDATE": "18/05/2020",
  "PRODUCT_LIST": [
    {
      "PRODUCT_NAME": "Avocado",
      "PRODUCT_PRICE": "R$ 10,50"
    },
    {
      "PRODUCT_NAME": "Avocado",
      "PRODUCT_PRICE": "R$ 10,50"
    },
    {
      "PRODUCT_NAME": "Potatoes",
      "PRODUCT_PRICE": "R$ 5,50"
    },
    {
      "PRODUCT_NAME": "Tomato",
      "PRODUCT_PRICE": "R$ 15,50"
    }
  ]
}
```

Thanks!

**Comment by amitsendinblue** [comment]
Hi @danieljoris, could you please confirm which API end point you are using and in which field you need to pass this information?

**Comment by amitsendinblue** [comment]
It will be great if you can provide the curl request.

**Comment by ghost** [comment]
@amitsendinblue I'm using this endpoint: [SMTPApi.SendTransacEmail()](https://github.com/sendinblue/APIv3-csharp-library/blob/master/docs/SMTPApi.md#sendtransacemail). | https://api.sendinblue.com/v3/smtp/email (POST)

I'm trying to pass Parameters. List of parameters like in [Json](https://github.com/sendinblue/APIv3-csharp-library/issues/10#issuecomment-606795487)

I think everything is okay in Sendinblue api, because I test with "normal" parameters(not nested params) and the result is OK. But when I try to send [Nested Parameters](https://github.com/sendinblue/APIv3-csharp-library/issues/10#issuecomment-606795487) I receive an error from API. "Parameters Invalid"

I'm checked the parameters names in Sendinblue Configuration and is Okay then I check parameters send in my api, everything is okay either.

And the code is:

```
Dictionary<string, object> parametersList = new Dictionary<string,object>();
Dictionary<string, string> nestedParameters = new Dictionary<string,string>();

nestedParameters("PRODUCT_NAME", "Avocado");
nestedParameters("PRODUCT_PRICE", "R$ 10,50");

parametersList.Add("COMPANYNAME", "Avocado");
parametersList.Add("DUEDATE", "18/05/2020");
parametersList.Add("PRODUCTS_LIST", nestedParameters);

var requestTransactionEmail = new SendSmtpEmail(
                sender,
                to,
                null,
                null,
                null,
                null,
                transactionalEmail.Subject,
                null,
                null,
                null,
                transactionalEmail.TemplateId,
                parametersList,
                null
                );
            CreateSmtpEmail result = _smtpApi.SendTransacEmail(requestTransactionEmail);
```
I tried to send an Json in parameters, but result an error either.

If you provide an example of send nested parameters [(like in this JSON)](https://github.com/sendinblue/APIv3-csharp-library/issues/10#issuecomment-606795487) to this endpoint **SendTransacEmail()**. 

I think that would solve the problem.

I will try get curl request!

**Comment by amitsendinblue** [comment]
Hi @danieljoristryideas, Below is the C# code for the json you have mentioned:

**JSON:-**

```
"params":{
  "COMPANYNAME": "Avocado",
  "DUEDATE": "18/05/2020",
  "PRODUCT_LIST": [
    {
      "PRODUCT_NAME": "Avocado",
      "PRODUCT_PRICE": "R$ 10,50"
    },
    {
      "PRODUCT_NAME": "Avocado",
      "PRODUCT_PRICE": "R$ 10,50"
    },
    {
      "PRODUCT_NAME": "Potatoes",
      "PRODUCT_PRICE": "R$ 5,50"
    },
    {
      "PRODUCT_NAME": "Tomato",
      "PRODUCT_PRICE": "R$ 15,50"
    }
  ]
}
```

**C# Code:-**
            
           
           JObject ProductListObj1 = new JObject();
            ProductListObj1.Add("PRODUCT_NAME", "Avocado");
            ProductListObj1.Add("PRODUCT_PRICE", "R$ 10,50");

            JObject ProductListObj2 = new JObject();
            ProductListObj2.Add("PRODUCT_NAME", "Avocado");
            ProductListObj2.Add("PRODUCT_PRICE", "R$ 10,50");

            JObject ProductListObj3 = new JObject();
            ProductListObj3.Add("PRODUCT_NAME", "Potatoes");
            ProductListObj3.Add("PRODUCT_PRICE", "R$ 5,50");

            JObject ProductListObj4 = new JObject();
            ProductListObj4.Add("PRODUCT_NAME", "Tomato");
            ProductListObj4.Add("PRODUCT_PRICE", "R$ 15,50");


            JArray ProductList = new JArray();
            ProductList.Add(ProductListObj1);
            ProductList.Add(ProductListObj2);
            ProductList.Add(ProductListObj3);
            ProductList.Add(ProductListObj4);


            JObject Params = new JObject();
            Params.Add("COMPANYNAME", "Avocado");
            Params.Add("DUEDATE", "18/05/2020");
            Params.Add("PRODUCT_LIST",ProductList);

Let me know if you still face any issue.

Thanks,
Amit Joshi

**Comment by amitsendinblue** [comment]
Hi @danieljoristryideas, hope this issue is resolved from above mentioned solution, so closing this issue now.
Thanks,
Amit Joshi
