### ISSUE TITLE
sib_api_v3_sdk.Client.Configuration' threw an exception

### ISSUE THREAD

**Issue by krishna666-tech** [sendinblue/APIv3-csharp-library#16]
Hi
I have an issue using this sdk.
Below is the error.

{"Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 
(Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}
But i have all the dependencies added through nuget.

**Comment by amitsendinblue** [comment]
Hi @krishna666-tech, Could you please share more details like .NET version of your application, type of your application and a sample piece of code or any screenshot or video so that we can investigate the issue and help you better.
Thanks

**Comment by amitsendinblue** [comment]
Closing the issue because of no response, please feel free to reopen if you still face the issue with more details.
Thanks
