### ISSUE TITLE
GetEmailEventReport failed when Json response include subject has array.

### ISSUE THREAD

**Issue by jcarenton** [sendinblue/APIv3-csharp-library#19]
GetEmailEventReport failed when Json response include subject has array.

Unexpected character encountered while parsing value: [. Path 'events[1].subject', line 1, position 352.

{
   "events":[
      {
         "email":"to@gmail.com",
         "date":"2020-06-16T19:22:15.000-04:00",
         "subject":"Test subject",
         "messageId":"",
         "event":"requests",
         "tag":"",
         "from":"test@sender.org"
      },
      {
         "email":"to@gmail.com",
         "date":"2020-06-16T19:22:15.000-04:00",
         **"subject":[
            "Test subject"
         ]**,
         "messageId":"",
         "tag":"",
         "from":"test@sender.org"
      }
   ]
}

**Comment by amitsendinblue** [comment]
Hi @jcarenton, We are already aware from this issue and are activity working on it. We will update here as soon as the issue is fixed.
Thanks

**Comment by amitsendinblue** [comment]
Hello @jcarenton, sorry for the delay in response, the issue occurred due to some data inconsistency but it should be fine now, please feel free to reopen the issue if you still face this again.
Thanks
