### ISSUE TITLE
Embedding Images

### ISSUE THREAD

**Issue by m--c** [sendinblue/APIv3-csharp-library#20]
Hi! sorry for posting an issue here, but I couldnt find anything on the web. How can I embedd/inline images when sending with this api?
thanks in advance

**Comment by amitsendinblue** [comment]
Hi @m--c, Which API are you using and what do you want to send? Could you please elaborate more so that I can assist you better?
Thanks

**Comment by m--c** [comment]
Hi!
Basically, I want to embed images in the email's body. Dynamically generated images that cannot be sent as linked resources, such as qr codes or other generated visual elements. Most transactional email apis have such functionality, furthermore, I see this api used to have it. Embedded images are not really attachments. I could try to replicate the functionality by setting base 64 strings in the header and then linking these strings in the body, but I'd rater use buklt in functionality, if any. All other transactional email apis i currently support this.

thanks!

**Comment by amitsendinblue** [comment]
Hello @m--c,
Earlier we used to allow embed images in email body (in API V2) but we do not allow it now as this is outdated and may affect the email deliverability and the senders reputation also. We recommend you to use images as attachment (Base 64 content or attachment URL).
Thanks

**Comment by tastydev** [comment]
> Hello @m--c, Earlier we used to allow embed images in email body (in API V2) but we do not allow it now as this is outdated and may affect the email deliverability and the senders reputation also. We recommend you to use images as attachment (Base 64 content or attachment URL). Thanks

Hello @amitsendinblue , i am currently facing this topic too. Is it possible to link to an attached image through the filename inside the html? I didn't find a way to recieve the content-id of the attachmant or send it with the SIB/Brevo Api. So how can i use the attached images inside the html body? Is it supposed to work like this? Thanks for your help.

```html
<img src="myAttached.png" />
```

JFYI: I am not talking about static images, i am talking about dynamically generated images which needs to be shown inside the mail. Like an google maps static api image with a custom route for each email. Data URI won't work for most email clients so attachment seems to be the only solution?

**Comment by merijndk** [comment]
@tastydev did you figure out how to do this? Thanks in advance.

**Comment by m--c** [comment]
I add the images as base64 in the src , it is my understanding that bravo
still lacks this basic feature all other platforms offer.
