### ISSUE TITLE
No Transactional Attributes sent.

### ISSUE THREAD

**Issue by amedriveroperez1984** [sendinblue/APIv3-csharp-library#21]
I'm trying to send a "Template" but transactional attributes are not been shown properly in the result email.
The email is sent properly but the Transactional attributes are not replaced accordingly.

C# Code:
```
var notifierAPI = new SMTPApi();
notifierAPI.Configuration.AddDefaultHeader("api-key", _appSettings.Notifier_API_Key);

SendEmail email = new SendEmail(emailTo: new List<string>(), tags: new List<string>());
email.EmailTo.Add(to);
email.Attributes = new { ID = Guid.NewGuid(), LINKURL = $"{_appSettings.Client_Url}/forgotpassword?code={code}&user={to}" };
email.Tags.Add(EmailTemplatesEnum.PasswordForgotten.ToString());

 SendTemplateEmail result  = await notifierAPI.SendTemplateAsync((long)EmailTemplatesEnum.PasswordForgotten, email);
```

Find attached Transactional attributes config and Template definition.

<img width="1022" alt="Transactional Attributes" src="https://user-images.githubusercontent.com/13276976/96665225-6b015f80-1322-11eb-8480-8db506ce4d5b.png">
<img width="640" alt="Template" src="https://user-images.githubusercontent.com/13276976/96665229-6d63b980-1322-11eb-81da-b2dbcd15c9b9.png">

**Comment by pravin-sib** [comment]
Hi, 

Please note that currently, we replace the dynamic value for the following cases.

1. Normal attributes:

The client needs to define {{contact.attribute_name}} in his template and if the receipt contact is added in the client’s contact list and having the value for attribute_name, it would be replaced with that value in email.

Currently, we do not support this feature for the transactional attribute.
2. Transactional parameter:

The client needs to define {{params.attribute_name}} in his template design as you already did and then this value needs to pass in the API request in ‘params’ parameter (there is no need to save the link in transactional attributes) and it would be replaced as expected.

For example curl request:
------------------------------------------------------------
curl --request POST \
--url https://api.sendinblue.com/v3/smtp/email \
--header 'accept: application/json' \
--header 'api-key: YOUR API KEY' \
--header 'content-type: application/json' \
--data '{"sender":

{"name":"sender_name","email":"pravin.kumar@sendinblue.com"}
,"to":[

{"email":"pravin.kumar@sendinblue.com","name":"to_name"}
],"replyTo":

{"email":"pravin.kumar@sendinblue.com","name":"reply_to_name"}
,"params":

{"LINKURL":"http://sendinblue.com/"}
,"subject":"Test password reset link","templateId":123}'

------------------------------------------------------------------
C# example : 

private void Test_SendTransacEmail()
{
var apiInstance = new SMTPApi();

//Define Sender

string SenderName = "sender_name";
string SenderEmail = "pravin.kumar@sendinblue.com";
SendSmtpEmailSender Email = new SendSmtpEmailSender(SenderName, SenderEmail);

//Define Recipient

string ToEmail = "pravin.kumar@sendinblue.com";
string ToName = "to_name";
SendSmtpEmailTo smtpEmailTo = new SendSmtpEmailTo(ToEmail, ToName);
List<SendSmtpEmailTo> To = new List<SendSmtpEmailTo>();
To.Add(smtpEmailTo);

//Define BCC

string BccName = "bcc_name";
string BccEmail = "pravin.kumar@sendinblue.com";
SendSmtpEmailBcc BccData = new SendSmtpEmailBcc(BccEmail, BccName);
List<SendSmtpEmailBcc> Bcc = new List<SendSmtpEmailBcc>();
Bcc.Add(BccData);

//Define CC

string CcName = "cc_name";
string CcEmail = "pravin.kumar@sendinblue.com";
SendSmtpEmailCc CcData = new SendSmtpEmailCc(CcEmail, CcName);
List<SendSmtpEmailCc> Cc = new List<SendSmtpEmailCc>();
Cc.Add(CcData);

//Define HTML Content

string HtmlContent = "<h1>Hello this is test</h1>";

// Define Text content

string TextContent = "Hello this is test";

// Define Subject

string Subject = "Test Subject";

//Define Reply_to

string ReplyToName = "reply_to_name";
string ReplyToEmail = "pravin.kumar@sendinblue.com";
SendSmtpEmailReplyTo ReplyTo = new SendSmtpEmailReplyTo(ReplyToEmail, ReplyToName);

// Define attachment (URL and base64 format)

string AttachmentUrl = "http://img.mailinblue.com/2520615/attachments/Sendinblue.png";

string stringInBase64 = "<type base 64 encoded content of a file>";
byte[] Content = System.Convert.FromBase64String(stringInBase64);
string AttachmentName = "tesMyOdt.odt";

SendSmtpEmailAttachment AttachmentContent = new SendSmtpEmailAttachment(AttachmentUrl, Content, AttachmentName);
List<SendSmtpEmailAttachment> Attachment = new List<SendSmtpEmailAttachment>();
Attachment.Add(AttachmentContent);

//Define Headers

JObject Headers = new JObject();
Headers.Add("x-mailin-custom", "C#Test");

//Define TemplateId

long? TemplateId = 123;

//Define Params

JObject Params = new JObject();
Params.Add("LINKURL", "http://sendinblue.com/");

//Define Tags

List<string> Tags = new List<string>();
Tags.Add("C# Wrapper");

try

{ var sendSmtpEmail = new SendSmtpEmail(Email, To, Bcc, Cc, HtmlContent, TextContent, Subject, ReplyTo, Attachment, Headers, TemplateId, Params, Tags); CreateSmtpEmail result = apiInstance.SendTransacEmail(sendSmtpEmail); Debug.WriteLine(result.ToJson()); Console.WriteLine(result.ToJson()); Console.ReadLine(); }
catch (Exception e)

{ Debug.WriteLine(e.Message); Console.WriteLine(e.Message); Console.ReadLine(); }
}

**Comment by Napalmpje** [comment]
I ran into exactly the same issue, also using the SendTemplate method of the API instead of the SendTransacEmail.
It's only that I had to go to the source code to get a clue what the *** was going on.
Why not mark that method as [Obsolete] or so?

**Comment by amitsendinblue** [comment]
Hi @Napalmpje, The issue you are talking about is different - and in the reference document we have marked send a template API as deprecated and mentioned that it will stop working the 31st December 2020 at 00:00:00 UTC.
https://developers.sendinblue.com/reference#sendtemplate-1

The issue reported by @amedriveroperez1984 is about templating language which @pravin-sib has provided the resolution. 

Based on the above conversation closing this issue.
