### ISSUE TITLE
Deleting all contacts from a list has missing properties in response object

### ISSUE THREAD

**Issue by dbraillon** [sendinblue/APIv3-csharp-library#22]
Regarding the [API documentation](https://developers.sendinblue.com/reference#removecontactfromlist), **Delete a contact from a list** has three different uses cases. The third option allows the user to completely remove all users from a specific list. In that case, the response should give a **processId** to keep track of the completion state.

Neither [PostContactInfo](https://github.com/sendinblue/APIv3-csharp-library/blob/290f293e00ae3e23fa57439dd7ee1f38e6a6d117/src/sib_api_v3_sdk/Model/PostContactInfo.cs) nor [PostContactInfoContacts](https://github.com/sendinblue/APIv3-csharp-library/blob/290f293e00ae3e23fa57439dd7ee1f38e6a6d117/src/sib_api_v3_sdk/Model/PostContactInfoContacts.cs) have a **ProcessId** property.

I would like to open a PR to correct that. I guess I will just add as nullable property : **total** and **processId**. The user of that client API will have to check these properties or existing **Contacts** property depending on what option he used.

**Comment by amitsendinblue** [comment]
Resolved in latest release:- https://github.com/sendinblue/APIv3-csharp-library/releases/tag/v3.0.0
Closing this issue
