### ISSUE TITLE
SendEmail Attributes DataMember

### ISSUE THREAD

**Issue by ctreudler** [sendinblue/APIv3-csharp-library#25]
how to pass data in this array?

Error calling SendTemplate: {"code":"invalid_parameter","message":"attributes are not valid"}

**Comment by amitsendinblue** [comment]
Hi @ctreudler, could you please provide more details like the code you are using so that we can assist you better?
Below is the sample code to pass attributes for SendTemplate request:
```
            JObject attributes = new JObject();
            attributes.Add("FIRSTNAME", "AMIT");
            attributes.Add("LASTNAME", "JOSHI");

**Comment by amitsendinblue** [comment]
Hi @ctreudler, I hope above answer solved your issue, closing this issue due to no reply from more than 11 days. 

Thanks
