### ISSUE TITLE
SendEmail attributes don't show up on the template

### ISSUE THREAD

**Issue by Errox** [sendinblue/APIv3-csharp-library#26]
I'm using the following code while using the API. Only I can't get my params to show up within the mail. 

Am I missing something?

` Configuration.Default.AddApiKey("api-key", "Key");

            var apiInstance = new TransactionalEmailsApi();
            var templateId = 2;  
            string[] mails = { Mail };
            List<string> mailList = new List<string>(mails);

            JObject att = new JObject();
            att.Add("LASTNAME", "Kaas");
            att.Add("VIDEOCALLDATE", "2020-01-01");
            att.Add("VIDEOCALLTIME", "10:00");

            var sendEmail = new SendEmail(mailList, attributes:att); // SendEmail | 
            try
            {
                apiInstance.SendTemplate(templateId, sendEmail);
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception when calling TransactionalEmailsApi.SendTemplate: " + e.Message);
            }

            Console.WriteLine("Mail sent to: " + Mail);`

I'm using the following template to test the params. 
![2020-11-08 15_54_28-SendinBlue Responsive Template Builder - Brave](https://user-images.githubusercontent.com/10991347/98468498-ff9d0600-21da-11eb-8b17-e7cd9b002a78.png)

**Comment by amitsendinblue** [comment]
Hi @Errox, I checked with the provided API scripts and found that the you using the 'send a template' API V3 endpoint to send a transactional email https://developers.sendinblue.com/reference#sendtemplate-1.

Please note that the above-mentioned endpoint is marked as deprecated and it does not support the params and also you passed the params value in the attributes as well which is not correct. This is the reason behind params was not appeared in the email.

Also, it looks like that you designed template correctly for dynamic attribute. 
Please use the following endpoint to send a transactional email as it will support the params.
https://developers.sendinblue.com/reference#sendtransacemail

Thanks

**Comment by amitsendinblue** [comment]
For more information please refer following link:
https://github.com/sendinblue/APIv3-csharp-library/blob/master/docs/SMTPApi.md#sendtransacemail
