### ISSUE TITLE
Send Email - Wrong link url in email sent

### ISSUE THREAD

**Issue by amedriveroperez1984** [sendinblue/APIv3-csharp-library#27]
After upgrade to version 3.0.0 I'm sending a URL to my template, but the final link on email is landing on a 404 page that I don't know from where it came. 

**This is it**: [https://dcaaejj.r.bh.d.sendibt3.com/tr/cl/dsIH28ebVdB7XjbYVOP6f5RNmYyKJEXAERimvbloOjicqOYTOmU1-78vhABqUVDisZRcDydgiteqV-L_t7wB_8DJ22IXuXLWHsABuinwyjrAHatf4DTbyDn0UYdrGKbKswM7rHW1cqWUYN1X-EYk88pA](https://dcaaejj.r.bh.d.sendibt3.com/tr/cl/dsIH28ebVdB7XjbYVOP6f5RNmYyKJEXAERimvbloOjicqOYTOmU1-78vhABqUVDisZRcDydgiteqV-L_t7wB_8DJ22IXuXLWHsABuinwyjrAHatf4DTbyDn0UYdrGKbKswM7rHW1cqWUYN1X-EYk88pA)

**This is the attributes object that I've sent**:
`{{   "LINKURL": "http://localhost:4200/forgotpassword?code=CfDJ8IrsulHqjtlHn%2fHutPjNgpVJhuOyXH1p%2bCSSTNmwklFjcIcfvyXkK%2fehpqCH2JSBDWnn4TYg3d5QDCtTXycYdkoOm%2bQCWojNml3gU6y39OttVMIB5juzGsuYTh8haUpuuTiX%2fLcZmPi5IjFHlrGTLsduinoig2qiFO%2fPdACvsi8dLINgC6ny6Vmc47UDGwLCUJWMvyMcC3LcfrqZpS07NHkKfiRETMkl7Lw99SSmyQLv&user=amed@valid.com" }}`

**This is the template definition**: (Please inspect on Click Here link to see the parameter, I don't know GitHub shoes my code as a HTML not like a comment)

<div><span style="font-size:16px;">We received a request to reset your password for your account.</span></div>

<div><span style="font-size:16px;">&nbsp;</span></div>

<div><span style="font-size:16px;">Please go to the following URL to set a new password:&nbsp;<a href="{{params.LINKURL}}" style="text-decoration: underline; color: rgb(0, 146, 255);">Click here!</a></span></div>

<div><span style="font-size:16px;">&nbsp;</span></div>

<div><span style="font-size:16px;">If you didn&rsquo;t ask to change your password, don&rsquo;t worry! Your password is still safe and you can delete this email.</span></div>

<div><span style="font-size:16px;">&nbsp;</span></div>

<div>&nbsp;<span style="font-size:30px;">________________________________</span></div>

<div><span style="color:#d82f29;"><strong>Attention</strong>: This is a system automatically generated email, please do not reply.</span></div>

<div>&nbsp;</div>

**Comment by amedriveroperez1984** [comment]
Any updates on this??

**Comment by amitsendinblue** [comment]
Hi @amedriveroperez1984, Thank you for reporting this issue and it does not look a wrapper specific issue. 

I would request you to please try once using curl request also to be sure that is this the issue specific to c# client or the URL. 

Please report this issue with our support team from you account (https://account.sendinblue.com/support  --> please create a new ticket) and provide more details like the request payload you are using while creating the issue. As it might require further investigation and we will look into it.

Thanks
