### ISSUE TITLE
PARAMS missing on Emial sent.

### ISSUE THREAD

**Issue by amedriveroperez1984** [sendinblue/APIv3-csharp-library#28]
After upgrade to version 3.0.0 any of the PARAMS sent are been reflected on the result email.

Before there were rendered successfully.

**Comment by amedriveroperez1984** [comment]
**** Building Email info

public async Task<bool> SendLaneclosureReviewedEmail(int laneclosureId)
        {
            try
            {
                LaneClosureRequestDto laneclosure = await _laneClosureRequestRepository.FindDto(laneclosureId);
                string requestorEmail = (await _userManager.FindByIdAsync(laneclosure.RequestorId))?.Email;

                AppUser approver = await _userManager.FindByIdAsync(laneclosure.ReviewerId);
                string approverName = $"{approver?.Firstname} {approver?.Lastname}";

                SendSmtpEmailSender sender = GetSender();

                List<SendSmtpEmailTo> To = new List<SendSmtpEmailTo>();
                To.Add(new SendSmtpEmailTo(requestorEmail));
                To.Add(new SendSmtpEmailTo(approver?.Email));

                JObject Headers = new JObject();
                Headers.Add("x-mailin-custom", $"{_appSettings.Notifier_Sender_Name}:{EmailTemplatesEnum.LaneclosureReviewed.ToString()}");

                long TemplateId = (long)EmailTemplatesEnum.LaneclosureReviewed;

                string linkurl = $"{_appSettings.Client_Url}/laneclosure/{laneclosure.LaneclosureRequestId}";
                JObject Params = new JObject();
                Params.Add(_appSettings.Email_Template_LinkUrl_Key, linkurl);
                Params.Add(_appSettings.Email_Template_LCNumber_Key, laneclosure.Number);
                Params.Add(_appSettings.Email_Template_LCUser_Key, approverName);
                Params.Add(_appSettings.Email_Template_LCDate_Key, DateTime.Now.ToString("F"));

                List<string> Tags = new List<string>();
                Tags.Add(EmailTemplatesEnum.LaneclosureReviewed.ToString());

                await SendEmail(sender: sender, to: To, headers: Headers, templateId: TemplateId, _params: Params, tags: Tags);

                //Send Subscriptions notification
                return await SendSubscriptionNotificationEmail(laneclosure);
            }
            catch (Exception ex)
            {
                //TODO- Log exception info
                return false;
            }
        }

**Comment by amedriveroperez1984** [comment]
*****Common method to send emails
private async Task<bool> SendEmail(SendSmtpEmailSender sender, List<SendSmtpEmailTo> to, JObject headers, long templateId, JObject _params, List<string> tags)
        {
            try
            {
                var apiInstance = new TransactionalEmailsApi();
                if (!Configuration.Default.ApiKey.ContainsKey("api-key"))
                {
                    Configuration.Default.ApiKey.Add("api-key", _appSettings.Notifier_API_Key);
                }

                SendEmail Email = new SendEmail(emailTo: to.Select(t => t.Email).ToList(), headers: headers, attributes: _params, tags: tags);
                SendTemplateEmail result = await apiInstance.SendTemplateAsync(templateId, Email);

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

**Comment by amedriveroperez1984** [comment]
***** Template definition

A Lane Closure Request (#{{params.LCNUMBER}}) was reviewed by {{params.LCUSER}} at {{params.LCDATE}}, and is waiting for your review.
 
Please go to the following URL to review the Lane Closure Request: Click here!
 
Thanks.
Lane Closure Information System (https://www.site.com)

**Comment by amedriveroperez1984** [comment]
****Email sent

A Lane Closure Request (#) was reviewed by at , and is waiting for your review.
 
Please go to the following URL to review the Lane Closure Request: Click here!
 
Thanks.
Lane Closure Information System (https://www.site.com)

**Comment by amitsendinblue** [comment]
Hi @amedriveroperez1984, As far as I understood you want to pass params in the email, I would request you to please try below code once.
              
```
              Configuration.Default.ApiKey.Add("api-key", "xkeysib--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
	      var apiInstance = new TransactionalEmailsApi();
              string SenderName = "amit";
              string SenderEmail = "amit.joshi@sendinblue.com";
              SendSmtpEmailSender Email = new SendSmtpEmailSender(SenderName, SenderEmail);
              string ToEmail = "amit.joshi@sendinblue.com";
              string ToName = "Amit";
              SendSmtpEmailTo smtpEmailTo = new SendSmtpEmailTo(ToEmail, ToName);
              List<SendSmtpEmailTo> To = new List<SendSmtpEmailTo>();
              To.Add(smtpEmailTo);
              long? TemplateId = 48136;
              JObject Params = new JObject();
            Params.Add("name","Amit");
              try
              {
                  var sendSmtpEmail = new SendSmtpEmail(Email, To, null, null, null, null, null, null, null, null, TemplateId, Params, Tags);
                  CreateSmtpEmail result = apiInstance.SendTransacEmail(sendSmtpEmail);
                  Debug.WriteLine(result.ToJson());
                  Console.WriteLine(result.ToJson());
                  Console.ReadLine();
              }
              catch (Exception e)
              {
                  Debug.WriteLine(e.Message);
                  Console.WriteLine(e.Message);
                  Console.ReadLine();
              }
```

If issue still exists please report this issue with our support team from you account (https://account.sendinblue.com/support --> please create a new ticket) and provide more details like the request payload you are using while creating the issue. As it might require further investigation and we will look into it.

Thanks

**Comment by amedriveroperez1984** [comment]
Thanks!!! It works!!!
