### ISSUE TITLE
Classes Constructor design

### ISSUE THREAD

**Issue by AminEsmaeily** [sendinblue/APIv3-csharp-library#29]
Some classes have mandatory parameters and if the user doesn't pass them into the method from their constructor, they raise InvalidDataException at runtime. The following image shows that the constructor parameters are optional in `SendSmtpEmailSender` and `SendSmtpEmailTo` classes:
![1](https://user-images.githubusercontent.com/11803924/102654828-7f2cd600-4186-11eb-9f8b-3bf835a0d8c0.png)

I've set properties like this at first:
``` c#
var recipient = new SendSmtpEmailTo()
{
    email= emailAddress, 
    name= emailAddress
}
```

But it raised the exception. I got that the parameter values get checked in the [constructor method](https://github.com/sendinblue/APIv3-csharp-library/blob/04aa8e4722dcc74ac0f1ba750bd14ba1f3ddcfa7/src/sib_api_v3_sdk/Model/SendSmtpEmailSender.cs#L42) and they should be passed as the method parameters. I think it is better to change the required parameters from optional to mandatory.

**Comment by amitsendinblue** [comment]
Hi @AminEsmaeily, We have marked some fields as optional that were initially marked as required in the latest release. Please use the latest solution and let us know if you still face the issue.

Release:- https://github.com/sendinblue/APIv3-csharp-library/releases/tag/v3.1.0
Nuget:- https://www.nuget.org/packages/sib_api_v3_sdk/3.1.0

Thanks
