### ISSUE TITLE
SendTemplate fails silently when setting Attributes/Parameters

### ISSUE THREAD

**Issue by j-bbr** [sendinblue/APIv3-csharp-library#32]
I understand the endpoint is deprecated (in the documentation, the method unfortunately isn't marked obsolete) but setting attributes/parameters using this method just fails silently. A warning or even removing the method altogether would be preferable. I am under the impression that the preferred new way to do this is #28 but that could be better documented.

**Comment by amitsendinblue** [comment]
Hi @j-bbr, Thanks for the feedback, we will remove the method soon.
