### ISSUE TITLE
TransactionalEmailsApi : Sender is missing 

### ISSUE THREAD

**Issue by antoninkalk** [sendinblue/APIv3-csharp-library#34]
Hello, 

I am working on this issue for hours now and can't find the solution.

All my parameters are correctly set. 

Visual studio exception : 
![sendinbluefail](https://user-images.githubusercontent.com/66551222/112284468-91d51080-8c89-11eb-9e86-e3c9bca87a32.PNG)

Fiddler trace : 
![fiddler](https://user-images.githubusercontent.com/66551222/112284937-1031b280-8c8a-11eb-8ef4-f99e2198a414.PNG)

Thank you,

**Comment by amitsendinblue** [comment]
Hi @antoninkalk, First of all sorry for the late reply, somehow I missed to check the issue reported by you. 

It seems like the issue with passing incorrect inputs for the API. Please refer the example mentioned in the reference document ([link](https://developers.sendinblue.com/reference#sendtransacemail)). 

![image](https://user-images.githubusercontent.com/40165148/114694261-fab72200-9d37-11eb-95e3-c4e92d88adab.png)

Please feel free to reopen the issue if the given solution doesn't work for you.
Thanks
