### ISSUE TITLE
Error NU1605	Detected package downgrade

### ISSUE THREAD

**Issue by OPSnake** [sendinblue/APIv3-csharp-library#35]
Hello,

Remove reference of FubarCoder.RestSharp.xxx in package nuget for fix downgrade reference in project.
![image](https://user-images.githubusercontent.com/11973667/113940280-804d4600-97fd-11eb-8939-ec4ea97bfc37.png)

**Comment by amitsendinblue** [comment]
Hello @OPSnake, could you please elaborate more on this like which type of .net application you are using, the version of .net framework you are using and the exact issue which you are facing. So that we can investigate better.
FYI we support:
.NET Core >=1.0
.NET Framework >=4.6.1

**Comment by amitsendinblue** [comment]
Closing this as there is no response for more than 11 days.
