### ISSUE TITLE
Support of async calls in C#?

### ISSUE THREAD

**Issue by ewomack2000** [sendinblue/APIv3-csharp-library#37]
Hello, the API library is really easy to use, but does it work with async/await? I cannot get async/await to work using C#. Or is that wired in through the nuget layer?

**Comment by amitsendinblue** [comment]
Hi @ewomack2000,
C# does step by step execution by default, which means unless the first line is executed, the control will not move on to the next line.

If you could clarify the use-case and provide us with a sample script, we would be able to suggest a better solution.
As a sum up, if you just want to use the methods provided by our SDKs, then async/await is not really needed.
Please let us know if you have any further doubts.
Thanks
