### ISSUE TITLE
sib_api_v3_sdk.Model.GetLists is not strongly typed

### ISSUE THREAD

**Issue by EricBos** [sendinblue/APIv3-csharp-library#38]
The result is a list of type <Object>

If there was at least an Id, the call to the GetList for more details could be made. 
Now it's just Json.

Preferably sib_api_v3_sdk.Model.GetLists would contain the Id and Name

**Comment by amitsendinblue** [comment]
Hello @EricBos, I am sorry but I couldn't understand the issue, could you please explain little more with some example.
Thanks

**Comment by EricBos** [comment]
https://github.com/sendinblue/APIv3-csharp-library/blob/master/docs/GetLists.md returns a `List<Object>`
It would be great if it would return a `List<GetList>` e.g.

As far as I am aware the List is not customizable by a client, so it could be easily predicted what kind of properties there would be on that result.

**Comment by amitsendinblue** [comment]
Hi @EricBos,
The model `GetList` returns exhaustive data for a list but we return only limited properties for `GetLists` model. 
So the change you mentioned can not be implemented.
The possible list of properties that we return for `Getting all Lists` can be found in the reference doc. (screenshot attached below)

![image](https://user-images.githubusercontent.com/40165148/137164629-8c3171d8-505b-4f3b-b9e3-3a1625c2b252.png)
