### ISSUE TITLE
Issue creating new SendSmtpEmail object

### ISSUE THREAD

**Issue by MichaelRevolvo** [sendinblue/APIv3-csharp-library#4]
When trying to create a SendSmtpEmail object:

`var sendSmtpEmail = new SendSmtpEmail(){To = new List<SendSmtpEmailTo>() { new SendSmtpEmailTo() { Email = to, Name = ""} }};`

I get the following exception:

> "to is a required property for SendSmtpEmail and cannot be null"

It also happen when I follow the documentation and create an empty object:

`var sendSmtpEmail = new SendSmtpEmail()`

**Comment by Res42** [comment]
I'm not associated with SendinBlue, but I can provide some help.

If you check out the source code for the [SendSmtpEmail](https://github.com/sendinblue/APIv3-csharp-library/blob/d0fafcbcc3857da5be06bf39b777f899c7032562/src/sib_api_v3_sdk/Model/SendSmtpEmail.cs#L56-L60) class you can see that the default constructor checks if the `to` parameter is `null`. This throws your exception.

So the workaround is that you need to add the list of to addresses in the constructor, not in the object initializer. Like this:
```(csharp)
var sendSmtpEmail = new SendSmtpEmail(to: new List<SendSmtpEmailTo>() { new SendSmtpEmailTo() { Email = to, Name = "" } });
```
After this, you can use the object initializer for the other properties:
```(csharp)
var sendSmtpEmail = new SendSmtpEmail(to: new List<SendSmtpEmailTo>() { new SendSmtpEmailTo() { Email = to, Name = "" } })
{
    [... other properties ...]
};
```

**Comment by MichaelRevolvo** [comment]
> I'm not associated with SendinBlue, but I can provide some help.
> 
> If you check out the source code for the [SendSmtpEmail](https://github.com/sendinblue/APIv3-csharp-library/blob/d0fafcbcc3857da5be06bf39b777f899c7032562/src/sib_api_v3_sdk/Model/SendSmtpEmail.cs#L56-L60) class you can see that the default constructor checks if the `to` parameter is `null`. This throws your exception.
> 
> So the workaround is that you need to add the list of to addresses in the constructor, not in the object initializer. Like this:
> 
> ```
> var sendSmtpEmail = new SendSmtpEmail(to: new List<SendSmtpEmailTo>() { new SendSmtpEmailTo() { Email = to, Name = "" } });
> ```
> 
> After this, you can use the object initializer for the other properties:
> 
> ```
> var sendSmtpEmail = new SendSmtpEmail(to: new List<SendSmtpEmailTo>() { new SendSmtpEmailTo() { Email = to, Name = "" } })
> {
>     [... other properties ...]
> };
> ```

I don't know why that didn't come to mind. I guess I just rarely meet code that has validation rules in the constructor, even though it's supposed to be best practice. Thanks a lot!

**Comment by chriscfox** [comment]
That helped a lot thanks. I then had the same problem with the email attribute when initialising the SendSmtpEmailTo object.

**Comment by MrFishchev** [comment]
Please, reopen the issue. It is not fixed during the year...

**Comment by JeePeeTee** [comment]
This is based on the code generator of Swagger. The tool used to define this (client) API. The field **To** is marked as required and is checked in the construction of this object.
