### ISSUE TITLE
ContactsApi.GetContactInfo throws on non-existing contacts

### ISSUE THREAD

**Issue by EricBos** [sendinblue/APIv3-csharp-library#40]
The GetContactInfo (and all its variants) is throwing on a non-existing contact.
I cannot find a working alternative apart from downloading ALL contacts in a loop and then checking if that one contact already exists before Creating a new record.

According to the documentation here: https://developers.sendinblue.com/reference/contacts-7#getcontactinfo-1
The method should return a 404 when an item is not found when invoked as web api.

What would be wrong to return a null instead of throwing the exception?

Even the method GetContactInfoWithHttpInfo should return a status code 404 and an empty Data element imho.

Now it throws with this message:
{"code":"document_not_found","message":"Contact does not exist"}'

**Comment by amitsendinblue** [comment]
Hi @EricBos, 
It is expected that it will throw an exception in case of non existing contact. Since 404 is a non success status code.
You can access the error code being returned in the catch block using e.ErrorCode and implement your logic accordingly.
Below is the example for the same.

```
using sib_api_v3_sdk.Api;
using sib_api_v3_sdk.Client;
using sib_api_v3_sdk.Model;
using System;
using System.Diagnostics;

namespace Sendinblue
{
    class Program
    {
        static void Main(string[] args)
        {
            Configuration.Default.ApiKey.Add("api-key", "YOUR API KEY");

            var apiInstance = new ContactsApi();
            string email = "example@example.com";
            try
            {
                GetExtendedContactDetails result = apiInstance.GetContactInfo(email);
                Debug.WriteLine(result.ToJson());
                Console.WriteLine(result.ToJson());
                Console.ReadLine();
            }
            catch (ApiException e)
            {
               Console.WriteLine(e.ErrorCode);
                if(e.ErrorCode==404)
                    Console.WriteLine("do something");
                Console.WriteLine(e.Message);
                Console.ReadLine();
            }
        }
    }
}
```

**Comment by EricBos** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

Exception handling does not belong in normal application flow. (Maybe that's why it's called an Exception).

If there was a method that would allow checking if the contact would exist, that could be invoked without having an exception.
If without checking that, a contact would be created anyway, the exception would be valid.
