### ISSUE TITLE
Missing parameter for method GetTransacEmailsListAsync

### ISSUE THREAD

**Issue by EnjoyMachine** [sendinblue/APIv3-csharp-library#41]
The "limit" parameter is necessary in the url
The value must be an optional parameter in the method (By default it should be 500)

I have an exemple where you can see that if the parameter is not sent, I don't receive any values

With parameter:
![with-parameter](https://user-images.githubusercontent.com/47820810/131873430-b502b482-d4fd-4a93-8456-673f4987f21f.jpg)

Without parameter:
![without-parameter](https://user-images.githubusercontent.com/47820810/131873453-b9d2d159-aa40-4d6b-8738-84f894d36783.jpg)

**Comment by EnjoyMachine** [comment]
I can't add a branch in Github to add the solution so here is the file with the correction
[TransactionalEmailsApi.zip](https://github.com/sendinblue/APIv3-csharp-library/files/7104293/TransactionalEmailsApi.zip)

**Comment by amitsendinblue** [comment]
Hello @EnjoyMachine, Sorry for the late reply.
I tried same scenario with my test account it is working as expected for me - limit is optional parameter and getting results without limit parameter as well. It might be an account specific issue. 
I would request you to please report this issue with our support team from you account (https://account.sendinblue.com/support  --> please create a new ticket) as it might require further investigation and we will look into it. 
Thanks
