### ISSUE TITLE
Webhooks types/serialization

### ISSUE THREAD

**Issue by mausch** [sendinblue/APIv3-csharp-library#42]
Would be nice to add types and serialization functions for https://developers.sendinblue.com/docs/transactional-webhooks so I don't have to write and maintain that code myself 🙂

**Comment by amitsendinblue** [comment]
Hi @mausch, Could you please elaborate the suggestion a bit more?
Thanks

**Comment by mausch** [comment]
Map each event type to a C# type and make them deserializable with some standard library like System.Text.Json or Newtonsoft.

**Comment by amitsendinblue** [comment]
Hi @mausch,
This is an auto-generated code using swagger-codegen. It is difficult for us to make the changes at our end. 
Apologies, but for now you will have to go ahead with the work around you suggested.  
Thanks..!
