### ISSUE TITLE
When Adding the api-key: "The Key Already Existed In The Dictionary"

### ISSUE THREAD

**Issue by JeremyCaron** [sendinblue/APIv3-csharp-library#43]
I'm sure I must be missing something here, but after working with this API in my dotnet 5 ASP.NET Web API projects, I'm unclear on how best to proceed.  It's clear that setting the API key is meant to be done only once since the default configuration is static.  To accomplish this, I added this call to the constructor of my Startup class (that setting does have the API key):

`sib_api_v3_sdk.Client.Configuration.Default.ApiKey.Add("api-key", _allSettings.SendInBlue.ApiKey);`

This works fine at normal runtime, but when I run my unit tests, everything explodes with the error below unless I wrap the line above in a try catch, presumably because the tests are multi-threaded and call startup multiple times. I think I've confirmed this, because checking for the key before adding it is insufficient; there's always a thread where the key wasn't there when it checked, but was by the time it went to add it, resulting in this error.

There has to be a better way around this than a blind try/catch.  What do you recommend?

> Error Message:
>    System.ArgumentException : The key already existed in the dictionary.
>   Stack Trace:
>      at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)

Thanks.

**Comment by jap64** [comment]
Not sure if there's a better way but i just use the following check:

`
if (!Configuration.Default.ApiKey.ContainsKey("api-key"))
    Configuration.Default.ApiKey.Add("api-key", api_key);
`

**Comment by JeremyCaron** [comment]
Thanks @jap64, but that's exactly the check I was implying when I said:

>  I think I've confirmed this, because checking for the key before adding it is insufficient; there's always a thread where the key wasn't there when it checked, but was by the time it went to add it, resulting in this error.

**Comment by amitsendinblue** [comment]
Hi @JeremyCaron, 
Instead of using the default Configuration object which is static, please use the Configuration object instantiation.

Please use below code as a reference, I hope this will solve the purpose.

```
using sib_api_v3_sdk.Api;
using sib_api_v3_sdk.Client;
using sib_api_v3_sdk.Model;
using System;
using System.Diagnostics;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;namespace Sendinblue
{
class Program
{
static void Main(string[] args)
{
var header = new Dictionary<string, string> {

{ "defaultHeader", "" }
};
var apiPrefix = new Dictionary<string, string> {

{ "apiKeyPrefix", "" }
};
var apiKey = new Dictionary<string, string> {

{ "api-key", "API KEY OF CUSTOMER" }
};
var apiInstance = new TransactionalEmailsApi(new Configuration(header, apiKey, apiPrefix));
string SenderName = "John Doe";
string SenderEmail = "example@example.com";
SendSmtpEmailSender Email = new SendSmtpEmailSender(SenderName, SenderEmail);
string ToEmail = "example1@example1.com";
string ToName = "John Doe";
SendSmtpEmailTo smtpEmailTo = new SendSmtpEmailTo(ToEmail, ToName);
List<SendSmtpEmailTo> To = new List<SendSmtpEmailTo>();
To.Add(smtpEmailTo);
string BccName = "Janice Doe";
string BccEmail = "example2@example2.com";
SendSmtpEmailBcc BccData = new SendSmtpEmailBcc(BccEmail, BccName);
List<SendSmtpEmailBcc> Bcc = new List<SendSmtpEmailBcc>();
Bcc.Add(BccData);
string CcName = "John Doe";
string CcEmail = "example3@example2.com";
SendSmtpEmailCc CcData = new SendSmtpEmailCc(CcEmail, CcName);
List<SendSmtpEmailCc> Cc = new List<SendSmtpEmailCc>();
Cc.Add(CcData);
string HtmlContent = "<html><body><h1>This is my first transactional email params.parameter</h1></body></html>";
string TextContent = null;
string Subject = "My params.subject";
string ReplyToName = "John Doe";
string ReplyToEmail = "replyto@domain.com";
SendSmtpEmailReplyTo ReplyTo = new SendSmtpEmailReplyTo(ReplyToEmail, ReplyToName);
string AttachmentUrl = null;
string stringInBase64 = "aGVsbG8gdGhpcyBpcyB0ZXN0";
byte[] Content = System.Convert.FromBase64String(stringInBase64);
string AttachmentName = "test.txt";
SendSmtpEmailAttachment AttachmentContent = new SendSmtpEmailAttachment(AttachmentUrl, Content, AttachmentName);
List<SendSmtpEmailAttachment> Attachment = new List<SendSmtpEmailAttachment>();
Attachment.Add(AttachmentContent);
JObject Headers = new JObject();
Headers.Add("Some-Custom-Name", "unique-id-1234");
long? TemplateId = null;
JObject Params = new JObject();
Params.Add("parameter", "My param value");
Params.Add("subject", "New Subject");
List<string> Tags = new List<string>();
Tags.Add("mytag");
SendSmtpEmailTo1 smtpEmailTo1 = new SendSmtpEmailTo1(ToEmail, ToName);
List<SendSmtpEmailTo1> To1 = new List<SendSmtpEmailTo1>();
To1.Add(smtpEmailTo1);
Dictionary<string, object> _parmas = new Dictionary<string, object>();
_parmas.Add("params", Params);
SendSmtpEmailReplyTo1 ReplyTo1 = new SendSmtpEmailReplyTo1(ReplyToEmail, ReplyToName);
SendSmtpEmailMessageVersions messageVersion = new SendSmtpEmailMessageVersions(To1, _parmas, Bcc, Cc, ReplyTo1, Subject);
List<SendSmtpEmailMessageVersions> messageVersiopns = new List<SendSmtpEmailMessageVersions>();
messageVersiopns.Add(messageVersion);
try

{ var sendSmtpEmail = new SendSmtpEmail(Email, To, Bcc, Cc, HtmlContent, TextContent, Subject, ReplyTo, Attachment, Headers, TemplateId, Params, messageVersiopns, Tags); CreateSmtpEmail result = apiInstance.SendTransacEmail(sendSmtpEmail); Debug.WriteLine(result.ToJson()); Console.WriteLine(result.ToJson()); Console.ReadLine(); }
catch (Exception e)

{ Debug.WriteLine(e.Message); Console.WriteLine(e.Message); Console.ReadLine(); }
}
}
}
```
Please let us know if this solution doesn't work for you.
Thanks
