### ISSUE TITLE
NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

### ISSUE THREAD

**Issue by tamilcantroz** [sendinblue/APIv3-csharp-library#47]
Hi, when i try to install with nutget in my visual studio express 2013 :
PM> Install-Package sib_api_v3_sdk -Version 3.2.0

i got the following error : 
Install-Package : La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi.
Au niveau de ligne : 1 Caractère : 16
+ Install-Package <<<< sib_api_v3_sdk -Version 3.2.0
+ CategoryInfo : NotSpecified: (:) [Install-Package], WebException
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

could you give me the DLL and how to installa in my visual studio?
i am a novice... thanks

**Comment by tamilcantroz** [comment]
Hi adam,

i could work around the problem of nuget online by dowloading the package in my local folder and using the following line :

**PM> Install-Package sib_api_v3_sdk -Version 3.2.0 -Source C:\FRANCESCO\Project**

But i still get error :

**Installation de « sib_api_v3_sdk 3.2.0 ».
Installation de « sib_api_v3_sdk 3.2.0 » terminée.
Ajout de « sib_api_v3_sdk 3.2.0 » à HairCollection3.
Désinstallation de « sib_api_v3_sdk 3.2.0 ».
Désinstallation de « sib_api_v3_sdk 3.2.0 » terminée.
L'installation a échoué. Restauration en cours...
Install-Package : Impossible d’installer le package « sib_api_v3_sdk 3.2.0 ». Vous essayez d’installer ce package dans un projet ciblant « .NETFramework,Version=v4.5 », mais le package ne contient aucun fichier
de contenu ou référence d’assembly compatible avec cette infrastructure. Pour plus d’informations, contactez le créateur du package.
Au niveau de ligne : 1 Caractère : 16
+ Install-Package <<<< sib_api_v3_sdk -Version 3.2.0 -Source C:\FRANCESCO\Project
+ CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand**

What should i do?

**Comment by tamilcantroz** [comment]
Hi, i also saw here : 

https://github.com/sendinblue/APIv3-csharp-library

that you support this framework :

.NET Framework >=4.6.1
so i installed the 4.6.1 in my porject and still have the same problem :

Install-Package sib_api_v3_sdk -Version 3.2.0 -Source C:\FRANCESCO\Project
Installation de « sib_api_v3_sdk 3.2.0 ».
Installation de « sib_api_v3_sdk 3.2.0 » terminée.
Ajout de « sib_api_v3_sdk 3.2.0 » à HairCollection3.
Désinstallation de « sib_api_v3_sdk 3.2.0 ».
Désinstallation de « sib_api_v3_sdk 3.2.0 » terminée.
L'installation a échoué. Restauration en cours...
Install-Package : Impossible d’installer le package « sib_api_v3_sdk 3.2.0 ». Vous essayez d’installer ce package dans un projet ciblant « .NETFramework,Version=v4.6.1 », mais le package ne contient aucun fichi
er de contenu ou référence d’assembly compatible avec cette infrastructure. Pour plus d’informations, contactez le créateur du package.
Au niveau de ligne : 1 Caractère : 16
+ Install-Package <<<< sib_api_v3_sdk -Version 3.2.0 -Source C:\FRANCESCO\Project
+ CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

i really need help to resolve this, thanks

**Comment by amitsendinblue** [comment]
Hi @tamilcantroz, our latest version 3.2.0 is compatible with .NET Framework >=4.6.1, below is the video link for the reference.
https://www.loom.com/share/26e1c89c0ac5481bb1efb54538f1ce94?sharedAppSource=personal_library

This may be the issue with the visual studio express 2013
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/hh266747(v=vs.120)

Please check this out and let us know if you still face the issue.
Thanks

**Comment by tamilcantroz** [comment]
HI,
thanks for your answer.
I am acutallyi with  .NET Framework 4.6.1, could you tell me what the  .NET Framework of the example (code surce here) in order to install and try to generate the DLL from this project?
Thanks

**Comment by amitsendinblue** [comment]
Hello @tamilcantroz, sorry for the delay in response, 
As shown in the video also the code source is with >NET Framework 4.6.1 itself.
Thanks
