### ISSUE TITLE
Missing "limit" parameter for method GetTransacEmailsListAsync

### ISSUE THREAD

**Issue by EnjoyMachine** [sendinblue/APIv3-csharp-library#48]
Hi

The parameter "Limit" for the method "GetTransacEmailsListAsync" must be optionnal to fill because in some cases you can't receive data if this parameter is not sent to sendinblue.

He is the case to reproduce the problem :
We are the 29th of december 2021.
I send an email at nearly 5pm

So I call the api with the following parameters
messageId : "my message id"
startDate : 2021-12-29
endDate : 2021-12-29 (I can't send 2021-12-30, it will be refused by the API because it's in the future)

without parameter "limit", I receive 0 result
![without-limit](https://user-images.githubusercontent.com/47820810/147684479-66ef60b7-94f1-4bea-bce5-d5c1ff49743e.PNG)

As you can see, if I send "Limit" parameter with a value of 10 I will receive my result
![with-limit](https://user-images.githubusercontent.com/47820810/147684487-77eeddb4-f204-4cd2-a66e-311ca8997cfa.PNG)

Thanks in advance, it's not a big work to add this parameter

Happy new year :)

**Comment by amitsendinblue** [comment]
please try with latest release v3.3.0

**Comment by EnjoyMachine** [comment]
Perfect, thanks
