### ISSUE TITLE
Email Validation Error in SendSmtpEmailReplyTo.cs

### ISSUE THREAD

**Issue by The-Denno** [sendinblue/APIv3-csharp-library#57]
Hello,

we tried to send a transactional email with a replyTo parameter set.
The default reply address in the template is not set.

the following error is raised as exception:

"email is a required property for SendSmtpEmailReplyTo and cannot be null"
InvalidDataException("email is a required property for SendSmtpEmailReplyTo and cannot be null");

This seems to be a bug, we even tried it with only the email parameter, same problem.

![image](https://user-images.githubusercontent.com/97184968/186854333-a4d5824f-dd94-41aa-92fb-7f901e8e669f.png)

Thank you very much and best regards.

**Comment by oliverheywood451** [comment]
Just want to echo that I had the same problem with a different model.

```c#
var versions = new SendSmtpEmailMessageVersions()
{
    To = new List<SendSmtpEmailTo1>() { new SendSmtpEmailTo1("fake@email.com, null) }
};
```

This produces an exception "to is a required property for SendSmtpEmailMessageVersions and cannot be null".  To me, this is not expected. I understand the work around is to use the constructor method. But I imagine most devs using this library are experiencing this as a small friction. I believe this should be an easy fix - add a public parameter-less constructor to these models. Then in-line object initialization will use that constructor.

Thanks for the library :)

**Comment by amitsendinblue** [comment]
Hello @The-Denno, Tested at our end below code works fine for use, please try the below piece of code.
`SendSmtpEmailReplyTo ReplyTo = new SendSmtpEmailReplyTo(sender.Email, sender.Name);`
