### ISSUE TITLE
Incompatible with Newtonsoft.Json version 12.03 or newer

### ISSUE THREAD

**Issue by larshjohannesson** [sendinblue/APIv3-csharp-library#58]
class sib_api_v3_sdk.Configuration.Default fails to initialize if my application is using Newtonsoft.Json version 12.0.3 or later.
With version 12.0.2 of Newtonsoft it is working fine.

The error which is thrown is as follows:

    The type initializer for 'sib_api_v3_sdk.Client.Configuration' threw an exception.
    at sib_api_v3_sdk.Client.Configuration.get_Default()

**Comment by amitsendinblue** [comment]
Hello @larshjohannesson, I will check this on my side in next release.

**Comment by amitsendinblue** [comment]
Fixed in latest release - v4.0.2 kindly refer the latest version.
