### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by PetesBreenCoding** [sendinblue/APIv3-csharp-library#60]
Hi, is it possible to pass an instance of HttpClient to the TransactionalEmailsApi class? HttpClient works most efficiently if you re-use the same instance across your application, so would like to re-use it.

**Comment by amitsendinblue** [comment]
Hello @PetesBreenCoding, It is an autogenerated code using swaggerCodeGen. It would be difficult to make the changes in our side but you can make the use the HttpClient in your application as the way you want.
