### ISSUE TITLE
Return object of SendTransecEmail not matching the documentation

### ISSUE THREAD

**Issue by AKruimink** [sendinblue/APIv3-csharp-library#61]
When calling TransactionalEmailAPi.SendTransacEmail the returned object only contains an optional MessageId or list of MessageID's but when checking the actuall documentation I would expect to the the returned object contain a list of IPs defining an id, ip and domain, or an error response with code and message.

Am I missing something obviouse here?

**Comment by amitsendinblue** [comment]
Hi @AKruimink,
We provide only the MessageId or list of MessageID's, here is the link of actual documentation - https://developers.sendinblue.com/reference/sendtransacemail
