### ISSUE TITLE
Error converting value "rejected" when calling GetSmsEventsAsync

### ISSUE THREAD

**Issue by RobertmSI** [sendinblue/APIv3-csharp-library#64]
Hello.
I am getting an error when calling GetSmsEventsAsync(...). 
Seems like the status "rejected" is missing in GetSmsEventReportEvents.EventNum ...
I am using version 3.3.0

sib_api_v3_sdk.Client.ApiException: Error converting value "rejected" to type 'System.Nullable`1[sib_api_v3_sdk.Model.GetSmsEventReportEvents+EventEnum]'. Path 'events[0].event', line 1, position 127. at sib_api_v3_sdk.Client.ApiClient.Deserialize(IRestResponse response, Type type) at sib_api_v3_sdk.Api.TransactionalSMSApi.GetSmsEventsAsyncWithHttpInfo(Nullable`1 limit, String startDate, String endDate, Nullable`1 offset, Nullable`1 days, String phoneNumber, String _event, String tags, String sort) at sib_api_v3_sdk.Api.TransactionalSMSApi.GetSmsEventsAsync(Nullable`1 limit, String startDate, String endDate, Nullable`1 offset, Nullable`1 days, String phoneNumber, String _event, String tags, String sort)

Please check...
Thank you!

**Comment by amitsendinblue** [comment]
Hello @RobertmSI,
We will add this feature in upcoming release and update here.

**Comment by amitsendinblue** [comment]
Fixed in latest release - v4.0.2 kindly refer the latest version.
