### ISSUE TITLE
The ext_id property is missing in contact creation

### ISSUE THREAD

**Issue by matchab** [sendinblue/APIv3-csharp-library#66]
Hello there,

I'm currently trying to create a contact with an external ID, with the ext_id property which is [documented here](https://developers.sendinblue.com/reference/createcontact). But it looks like the NuGet doesn't support this property at the moment.

Do you plan to implement this feature in the NuGet anytime soon?

Thanks,

**Comment by Lycrosa** [comment]
I would also like to know that.

**Comment by diego-at** [comment]
Same here, adding it to the api post with the nodejs client doesnt add anything to the contact object.

**Comment by djowebdev** [comment]
Same here ... 
I guess the only way to handle that is as an attribute right?

**Comment by matchab** [comment]
> Same here ... I guess the only way to handle that is as an attribute right?

From my tests, I have come to the conclusion that the ext_id field actually doesn't exist as a built-in feature. I mean, it's really not documented anywhere else, and it doesn't appear in the Brevo's admin panel... So yeah, I guess using a custom contact attribute is the way to go.

**Comment by amitsendinblue** [comment]
Fixed in the latest version brevo_csharp (1.0.0) - https://www.nuget.org/packages/brevo_csharp/
