### ISSUE TITLE
Brevo API Endpoint migration

### ISSUE THREAD

**Issue by sloury** [sendinblue/APIv3-csharp-library#67]
Hi,

The new Brevo documentation (https://developers.brevo.com/docs/how-it-works#endpoints) and the new API endpoints is now : https://api.brevo.com/v3/. 
The old endpoint is still working for now https://api.sedninblue.com/v3/ but we don't know how long is still working.

Thanks,

**Comment by orosbogdan** [comment]
Bump

**Comment by maftieu** [comment]
Any news?

**Comment by amitsendinblue** [comment]
Fixed in the latest version brevo_csharp (1.0.0) - https://www.nuget.org/packages/brevo_csharp/

**Comment by maftieu** [comment]
Can Brevo CSharp be open sourced?
The repository linked in nuget does not exists https://github.com/getbrevo/brevo-csharp

**Comment by maftieu** [comment]
Thanks, it's now accessible :)
