### ISSUE TITLE
SendSmtpEmailMessageVersions does not contain htmlContent

### ISSUE THREAD

**Issue by kimrohdin** [sendinblue/APIv3-csharp-library#68]
Should not SendSmtpEmailMessageVersions contains field htmlContent? If we want to send bulk mails with different content.

Looks like it should contain field in documentation:
https://developers.brevo.com/docs/batch-send-transactional-emails

![image](https://github.com/sendinblue/APIv3-csharp-library/assets/35214576/5b068e21-5990-4edb-8474-25e0900d07ef)

**Comment by dvdnhm** [comment]
+1

**Comment by amitsendinblue** [comment]
Fixed in the latest version brevo_csharp (1.0.0) -  https://www.nuget.org/packages/brevo_csharp/
