### ISSUE TITLE
A few samples would be nice - Send an email

### ISSUE THREAD

**Issue by MSIH** [sendinblue/APIv3-csharp-library#69]
Would be nice if you could create a solution that included a few project examples:

- send an email
- create/add user

**Comment by amitsendinblue** [comment]
Hello,
All samples are updated in the reference document - https://developers.brevo.com/reference
For Ex: - Send an Email - https://developers.brevo.com/reference/sendtransacemail
![image](https://github.com/sendinblue/APIv3-csharp-library/assets/40165148/f8a2f697-6fc6-44f4-8b7f-800e20f4db3a)
