### ISSUE TITLE
call to sendinblue webservice working ONLY ONCE

### ISSUE THREAD

**Issue by nicolacardi** [sendinblue/APIv3-csharp-library#70]
I have created a webservice in C# like this

`using Microsoft.AspNetCore.Mvc;
using System;
using sib_api_v3_sdk.Api;
using sib_api_v3_sdk.Client;
using sib_api_v3_sdk.Model;
using System.Collections.Generic;

namespace SwappX.Controllers
{
    [ApiController]
    [Route("api/[controller]")]

    public class MailController : ControllerBase
    {
        [Route("[action]/{mailAddress}")]
        [HttpGet]
        public  ActionResult sendEmail(string mailAddress)
        {

            Configuration.Default.ApiKey.Add("api-key", "MYAPIKEY");
            var apiInstance = new TransactionalEmailsApi();
            string SenderName = "Nicola Cardi";
            string SenderEmail = "example@example.com";
            SendSmtpEmailSender Email = new SendSmtpEmailSender(SenderName, SenderEmail);

            string ToEmail = mailAddress;
            string ToName = "Nicola Cardi";
            SendSmtpEmailTo smtpEmailTo = new SendSmtpEmailTo(ToEmail, ToName);
            List<SendSmtpEmailTo> To = new List<SendSmtpEmailTo>();
            To.Add(smtpEmailTo);

            string BccName = "";
            string BccEmail = "";
            SendSmtpEmailBcc BccData = new SendSmtpEmailBcc(BccEmail, BccName);
            List<SendSmtpEmailBcc> Bcc = new List<SendSmtpEmailBcc>();
            Bcc.Add(BccData);

            string CcName = "";
            string CcEmail = "";
            SendSmtpEmailCc CcData = new SendSmtpEmailCc(CcEmail, CcName);
            List<SendSmtpEmailCc> Cc = new List<SendSmtpEmailCc>();
            Cc.Add(CcData);

            string HtmlContent = "test";
            string TextContent = null;
            string Subject = "titolo mail";
          
            try
            {
                var sendSmtpEmail = new SendSmtpEmail(Email, To, null, null, HtmlContent, TextContent, Subject);
                CreateSmtpEmail result = apiInstance.SendTransacEmail(sendSmtpEmail);
                //Console.WriteLine(result.ToJson());
                //Console.WriteLine(result.ToJson());
                //Console.ReadLine();
                return Ok(result.ToJson());
            }
            catch (Exception e)
            {
                return BadRequest("Errore di invio"+e.Message);
            }

        }
        }

}`

This is part of a very large application that has several webservices published via IIS and they work properly.

In the swagger tester this mail sending webservice works perfectly: everytime I enter an email address it sends properly the email. I can use it tens of times and it works.

Now the issue:

When I publish this webservice via IIS  it works ONLY ONCE. 
If from the browser I call the api the program sends properly the email and responds with the details.
But if I do it again it doesn't work(!).
And I can try millions of times it will not work. It works again and **only once**, only if stop and restart IIS...
Is there any reason I could investigate or any hint to test better?
Thanks
Nicola

**Comment by amitsendinblue** [comment]
Hello @nicolacardi,
After carefully reviewing the details you provided, it appears that the issue might be related to either the IIS configuration or how the API call is handled in the code on your end.

Unfortunately, as this seems to be a configuration or implementation issue specific to your environment, we may not be able to directly assist with resolving it. Please let us know if you face any issue where our SDK receives the request but returning unexpected response.

Thank you.
