### ISSUE TITLE
Doubts with "SendSmtpEmailTo1" and "SendSmtpEmailReplyTo1"

### ISSUE THREAD

**Issue by fabr2004** [sendinblue/APIv3-csharp-library#76]
At documentation model list ([here](https://github.com/sendinblue/APIv3-csharp-library/blob/master/README.md#documentation-for-models)) I see:

1. **SendSmtpEmailTo** AND **SendSmtpEmailTo1**
2. **SendSmtpEmailReplyTo** AND **SendSmtpEmailReplyTo1**

I see no difference among each version.
Could it please be clarified?

**Comment by amitsendinblue** [comment]
Hello @fabr2004,
There is no such difference in both, this library is generated using Codegen and it generated two files for this, as while sending multiple message versions in transaction email, there it has used SendSmtpEmailTo1. You can refer to SendSmtpEmailTo only.
Thanks
